@startuml

class Shapes
{
    -=x1
    -=y1
    --
    =square()
    =perimeter()
    =move()
    =fill()
    =compare()
    =is_intersect()
    =is_include()
}

class C1
{
    -x2
    -y2
    -title
    -s_list
    --
    square()
    perimeter()
    move()
    fill()
}

class C2
{
    -x2
    -y2
    -x3
    -y3
    -x4
    -y4
    -title
    -area
    -color
    -s_list
    --
    square()
    perimeter()
    move()
    fill()
}

class C3
{
    -x2
    -y2
    -x3
    -y3
    -x4
    -y4
    -title
    -area
    -color
    -s_list
    --
    square()
    perimeter()
    move()
    fill()
}

C1 -> Shapes
C2 -> Shapes
C3 -> Shapes

@enduml