@startuml

class Shapes
{
    -=x1
    -=y1
    --
    =def square()
    =def perimeter()
    =def move()
    =def fill()
    =def compare()
    =def is_intersect()
    =def is_include()
}

class C1
{
    -x2
    -y2
    -title
    -s_list
    --
    def square()
    def perimeter()
    def move()
    def fill()
}

class C2
{
    -x2
    -y2
    -x3
    -y3
    -x4
    -y4
    -title
    -area
    -color
    -s_list
    --
    def square()
    def perimeter()
    def move()
    def fill()
}

class C3
{
    -x2
    -y2
    -x3
    -y3
    -x4
    -y4
    -title
    -area
    -color
    -s_list
    --
    def square()
    def perimeter()
    def move()
    def fill()
}

C1 -> Shapes
C2 -> Shapes
C3 -> Shapes

@enduml